services:

  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: mosquito_dashboard
      MYSQL_USER: webuser
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "3306:3306"
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - ./mysql:/var/lib/mysql
    networks:
      - network

networks:
  network:
    driver: bridge
